// Product acceptance on the real isolated DSH UI; no paid provider requests.
import {chromium,request} from 'playwright-core';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import path from 'node:path';
import assert from 'node:assert/strict';
const url=process.env.DSH_TEST_URL;assert.ok(url);const out=path.resolve(process.env.DSH_V03_REPORT_DIR||'artifacts/verification/v0.3/ui');await mkdir(out,{recursive:true});
const restart=process.env.DSH_V03_RESTART==='1',native=!!process.env.DSH_NATIVE_CDP;
const report={version:'0.3.0',startedAt:new Date().toISOString(),surface:native?'owned official DSH Desktop, physically installed final package':'official isolated DSH Web',archiveSha256:process.env.DSH_PACKAGE_SHA,realProvider:false,restart,checks:[],errors:[]};
const api=await request.newContext();await api.get(url);const base=new URL(url).origin;
async function call(endpoint,payload={}){const response=await api.post(base+'/api/video-studio/'+endpoint,{data:{type:'client-request',rpcId:randomUUID(),method:'video-studio/'+endpoint,payload}});assert.ok(response.ok());const value=await response.json();assert.equal(value.result.ok,true,JSON.stringify(value.result));return value.result.value;}
const browser=native?await chromium.connectOverCDP(process.env.DSH_NATIVE_CDP):await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),context=native?browser.contexts()[0]:await browser.newContext({viewport:{width:1680,height:1140},deviceScaleFactor:2});
const page=native?context.pages().find(p=>p.url().startsWith('dsh-app://')):await context.newPage();assert.ok(page);page.on('pageerror',e=>report.errors.push(e.message));
let id,root,shotId,originalText;
function pass(name,evidence={}){report.checks.push({name,evidence});console.log(name);}
async function poll(check,timeout=40000){const start=Date.now();while(Date.now()-start<timeout){const value=await check();if(value)return value;await page.waitForTimeout(100);}throw new Error('State did not settle');}
async function current(){return call('current',{projectId:id});}
async function tab(name){await page.getByRole('tab',{name,exact:true}).click();}
async function openStudio(){await page.getByText('映流 · 视频工作台',{exact:true}).click();}
async function verifyVideo(){const video=page.locator('.vs-export-player video');await poll(()=>video.evaluate(v=>v.readyState>=2).catch(()=>false));await video.evaluate(v=>v.play());await page.waitForTimeout(400);const state=await video.evaluate(v=>({time:v.currentTime,width:v.videoWidth,height:v.videoHeight,error:v.error?.message??null,duration:v.duration}));assert.ok(state.time>0);assert.equal(state.width,320);assert.equal(state.height,180);assert.equal(state.duration,2);assert.equal(state.error,null);await video.evaluate(v=>v.pause());return state;}
try{
 if(restart){const previous=JSON.parse(await readFile(path.join(out,'verification.json'),'utf8'));({id,root,shotId,originalText}=previous.project);const restored=await current();assert.equal(restored.project.id,id);assert.equal(restored.project.outputs.length,2);assert.equal(restored.project.shots[0].params.text,originalText);const history=await call('history',{projectId:id});assert.equal(history.canRedo,true);assert.match((await call('source',{projectId:id,shotId})).js,/v03-draft-preserved/);pass('normal native restart restores latest complete engineering state, source, outputs and redo history',{revision:restored.project.revision,history:history.entries.length});
 }else{
  let value=await call('create',{title:'V03 完整制作流程 '+Date.now(),topic:'中文图文与音轨的本地验收',target:{width:320,height:180,fps:{num:12,den:1},audioMode:'none'}});id=value.project.id;root=value.root;const shots=value.project.shots.slice(0,2).map((shot,index)=>({...shot,durationFrames:12,params:{...shot.params,text:`第${index+1}镜头的可编辑标题`}}));shotId=shots[0].id;originalText=shots[0].params.text;
  value=await call('apply',{projectId:id,expectedRevision:value.project.revision,shots,shotOrder:shots.map(s=>s.id),targetDuration:2});
  const rate=24000,pcm=Buffer.alloc(rate*2*2),header=Buffer.alloc(44);for(let i=0;i<rate*2;i++)pcm.writeInt16LE(Math.round(Math.sin(2*Math.PI*440*i/rate)*1200),i*2);header.write('RIFF');header.writeUInt32LE(36+pcm.length,4);header.write('WAVEfmt ',8);header.writeUInt32LE(16,16);header.writeUInt16LE(1,20);header.writeUInt16LE(1,22);header.writeUInt32LE(rate,24);header.writeUInt32LE(rate*2,28);header.writeUInt16LE(2,32);header.writeUInt16LE(16,34);header.write('data',36);header.writeUInt32LE(pcm.length,40);
  value=await call('audio',{projectId:id,action:'import',name:'合成验收音.wav',mime:'audio/wav',dataBase64:Buffer.concat([header,pcm]).toString('base64')});await call('audio',{projectId:id,action:'add',assetId:value.project.assets.at(-1).id,role:'music',volume:.2,loop:true});
 }
 if(!native)await page.goto(url);else await page.reload();const welcome=page.getByRole('button',{name:'继续',exact:true});if(await welcome.waitFor({state:'visible',timeout:1000}).then(()=>true).catch(()=>false))await welcome.click();await openStudio();await page.getByRole('heading',{name:(await current()).project.title,exact:true}).waitFor();
 if(!restart){
  await page.locator('.vs-shotchip').first().click();await tab('前端源码');await page.getByRole('button',{name:'JS',exact:true}).click();const editor=page.getByLabel('JS 源码',{exact:true});await poll(()=>editor.inputValue().then(v=>v.includes('render')));const before=await editor.inputValue(),draft=before+'\n// v03-draft-preserved\n';await editor.fill(draft);await page.locator('.vs-shotchip').nth(1).click();await poll(()=>editor.inputValue().then(v=>!v.includes('v03-draft-preserved')));await page.locator('.vs-shotchip').first().click();await poll(()=>editor.inputValue().then(v=>v.includes('v03-draft-preserved')));await tab('影片预览');await page.getByRole('button',{name:'刷新预览',exact:true}).click();await page.getByText(/本工程有源码草稿/).first().waitFor();pass('draft survives shot and tab changes; rendering does not execute unsaved source');
  await page.reload();await openStudio();await page.getByRole('button',{name:'查看源码草稿',exact:true}).click();await tab('前端源码');await page.getByRole('button',{name:'JS',exact:true}).click();await poll(()=>page.getByLabel('JS 源码',{exact:true}).inputValue().then(v=>v.includes('v03-draft-preserved')));await page.getByRole('button',{name:'保存源码',exact:true}).click();await poll(async()=>!(await page.locator('.vs-draft-banner').count()));assert.match((await call('source',{projectId:id,shotId})).js,/v03-draft-preserved/);pass('DSH client reload restores per-shot draft; explicit save submits canonical source');
  await poll(async()=>(await current()).task?.status!=='running');const browserPath=(await current()).environment.browserPath;await call('environment',{projectId:id,browserPath:'/bin/false'});await page.getByRole('button',{name:'导出视频',exact:true}).click();const failed=await poll(async()=>{const state=await current();return state.task?.status==='failed'?state.task:false;});await tab('任务记录');const record=page.locator(`[data-task-id="${failed.id}"]`);await record.waitFor();assert.ok(await record.getByRole('button',{name:'以当前工程重试',exact:true}).count());await call('environment',{projectId:id,browserPath});await record.getByRole('button',{name:'以当前工程重试',exact:true}).click();let done=await poll(async()=>{const state=await current();return state.task?.status==='complete'?state:false;},120000);assert.equal(done.task.retryOf,failed.id);assert.equal(done.project.outputs.length,1);pass('failed real Chromium export is recorded; UI retry after correcting environment produces actual MP4',{failed:failed.id,retry:done.task.id,frames:done.project.outputs[0].frameCount});
  await page.getByRole('button',{name:'导出视频',exact:true}).click();done=await poll(async()=>{const state=await current();return state.task?.status==='complete'&&state.project.outputs.length===2?state:false;},120000);await poll(()=>page.getByRole('button',{name:'导出视频',exact:true}).isEnabled());await tab('历史成片');assert.equal(await page.locator('.vs-export-record').count(),2);await page.locator('.vs-export-record').last().getByRole('button',{name:'播放成片',exact:true}).click();const oldVideo=await verifyVideo();await page.getByRole('button',{name:'关闭播放',exact:true}).click();await page.locator('.vs-export-record').first().getByRole('button',{name:'播放成片',exact:true}).click();pass('both old and new AAC MP4 outputs are independently playable in native plugin panel',{older:oldVideo,newer:await verifyVideo()});await page.screenshot({path:path.join(out,'historical-outputs.png')});
  await page.locator('.vs-shotchip').first().click();await page.getByLabel('屏幕主文字',{exact:true}).fill('可撤销的手动修改');await poll(async()=>(await current()).project.shots[0].params.text==='可撤销的手动修改');await tab('修改历史');await page.locator('.vs-record-panel').getByRole('button',{name:'撤销',exact:true}).click();await poll(async()=>(await current()).project.shots[0].params.text===originalText);await page.reload();await openStudio();await tab('修改历史');await page.locator('.vs-record-panel').getByRole('button',{name:'重做',exact:true}).click();await poll(async()=>(await current()).project.shots[0].params.text==='可撤销的手动修改');await page.locator('.vs-record-panel').getByRole('button',{name:'撤销',exact:true}).click();await poll(async()=>(await current()).project.shots[0].params.text===originalText);pass('persistent history restores manual changes after client reload with monotonic revisions',{revision:(await current()).project.revision});
  const libraryTitle='V03 可继续编辑的影片 '+id.slice(-6);await page.getByRole('button',{name:'工程列表',exact:true}).click();const original=page.locator(`[data-project-id="${id}"]`);await original.getByRole('button',{name:'重命名',exact:true}).click();await page.getByLabel('新的影片名称',{exact:true}).fill(libraryTitle);await page.getByRole('dialog',{name:'重命名影片',exact:true}).getByRole('button',{name:'保存',exact:true}).click();await original.getByRole('button',{name:'复制工程',exact:true}).click();await page.getByRole('dialog',{name:'复制影片工程',exact:true}).getByRole('button',{name:'保存',exact:true}).click();const copied=await poll(async()=>{const list=await call('list');return list.projects.find(p=>p.title===libraryTitle+' 副本');});const copy=await call('current',{projectId:copied.id});assert.equal(copy.project.outputs.length,0);assert.deepEqual(copy.project.sessionIds??[],[]);await page.getByRole('button',{name:'工程列表',exact:true}).click();await page.locator(`[data-project-id="${copied.id}"]`).getByRole('button',{name:'归档',exact:true}).click();await page.getByRole('button',{name:/^已归档 /}).click();await page.locator(`[data-project-id="${copied.id}"]`).getByRole('button',{name:'恢复工程',exact:true}).click();await page.getByRole('button',{name:/^正在创作 /}).click();await page.getByLabel('搜索影片工程',{exact:true}).fill(libraryTitle);assert.equal(await page.locator('.vs-project-card').count(),2);pass('real project library renames, copies independently, archives/restores and searches projects',{copyId:copied.id});await page.screenshot({path:path.join(out,'project-library.png')});await page.locator(`[data-project-id="${id}"] .vs-project-card-title`).click();await tab('修改历史');
  await page.locator('.vs-shotchip').first().click();await page.getByLabel('屏幕主文字',{exact:true}).fill('供正常重启检查的可重做修改');await poll(async()=>(await current()).project.shots[0].params.text==='供正常重启检查的可重做修改');await page.locator('.vs-record-panel').getByRole('button',{name:'撤销',exact:true}).click();await poll(async()=>(await current()).project.shots[0].params.text===originalText);await poll(async()=>(await call('history',{projectId:id})).canRedo);pass('an explicit content edit is undone after library management, leaving persisted redo for the normal restart');
 }else{await tab('历史成片');assert.equal(await page.locator('.vs-export-record').count(),2);await page.locator('.vs-export-record').last().getByRole('button',{name:'播放成片',exact:true}).click();pass('actual historical MP4 remains playable after normal native restart',await verifyVideo());await tab('任务记录');await poll(()=>page.locator('.vs-task-record').count().then(count=>count>=3));pass('persistent completed/failed/retry task records are visible after restart',{tasks:await page.locator('.vs-task-record').count()});await page.screenshot({path:path.join(out,'restart-tasks.png')});}
 report.project={id,root,shotId,originalText};report.finalState=await current();assert.deepEqual(report.errors,[]);report.status='PASS';
}catch(error){report.status='FAIL';report.failure=error.stack;await page.screenshot({path:path.join(out,restart?'restart-failure.png':'failure.png')}).catch(()=>{});throw error;}
finally{report.completedAt=new Date().toISOString();await writeFile(path.join(out,restart?'restart.json':'verification.json'),JSON.stringify(report,null,2)+'\n');await api.dispose();await browser.close();}
