import { useState } from 'react';
import type { ProjectLocation } from '../shared/types.ts';
import type { StudioController } from './controller.ts';
import { localTime } from './project-format.ts';

export function ProjectHome({controller,projects,loading,onCreate,onOpenDirectory}:{controller:StudioController;projects:ProjectLocation[];loading:boolean;onCreate:()=>void;onOpenDirectory:()=>void}){
  const [query,setQuery]=useState(''),[archived,setArchived]=useState(false),[manage,setManage]=useState<{project:ProjectLocation;action:'rename'|'duplicate'}|null>(null),[title,setTitle]=useState(''),[error,setError]=useState('');
  const visible=projects.filter(project=>!!project.archived===archived&&`${project.title} ${project.path}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  const busy=controller.getSnapshot().pending;
  async function open(project:ProjectLocation){try{setError('');await controller.focusProject(project.id);}catch(cause){setError(cause instanceof Error?cause.message:'工程打开失败');}}
  async function archive(project:ProjectLocation){const success=await controller.action(project.archived?'restore':'archive',{projectId:project.id},project.archived?'工程已恢复。':'工程已归档，文件保留，可随时恢复。');if(success)await controller.refreshProjects();}
  async function submit(){if(!manage||!title.trim())return;setError('');if(await controller.action(manage.action,{projectId:manage.project.id,title:title.trim()},manage.action==='duplicate'?'工程副本已创建。':'工程名称已更新。')){setManage(null);await controller.refreshProjects();}}
  return <section className="vs-project-home" aria-label="影片工程列表">
    <div className="vs-library-intro"><span className="vs-eyebrow">YOUR LOCAL FILMS</span><h2>我的影片工程</h2><p>在 DSH 会话中与模型沟通创作；在这里管理工程、查看镜头和导出的影片。</p><div className="vs-library-actions"><button className="vs-primary" onClick={onCreate} disabled={busy}>新建项目</button><button onClick={onOpenDirectory} disabled={busy}>打开工程目录</button>{controller.getSnapshot().snapshot?.project&&<button onClick={controller.showStudio}>继续当前工程 ↗</button>}</div></div>
    <div className="vs-library-heading"><div className="vs-library-tabs"><button aria-pressed={!archived} className={!archived?'is-active':''} onClick={()=>setArchived(false)}>正在创作 {projects.filter(p=>!p.archived).length}</button><button aria-pressed={archived} className={archived?'is-active':''} onClick={()=>setArchived(true)}>已归档 {projects.filter(p=>p.archived).length}</button></div><input type="search" aria-label="搜索影片工程" placeholder="搜索工程名称或目录…" value={query} onChange={event=>setQuery(event.target.value)}/><button onClick={()=>void controller.refreshProjects()} disabled={loading}>刷新列表</button></div>
    {error&&<p className="vs-inline-error" role="alert">{error}</p>}
    {loading?<p className="vs-library-empty">正在读取工程…</p>:!visible.length?<div className="vs-library-empty"><h3>{query?'没有匹配工程':archived?'暂无归档工程':'从一个想法开始'}</h3><p>{archived?'归档仅从创作列表隐藏，工程文件仍保留。':'新建影片，或打开包含 project.json 的现有工程目录。'}</p></div>:<div className="vs-project-grid">{visible.map(project=><article className={`vs-project-card ${project.archived?'is-archived':''}`} key={project.id} data-project-id={project.id}><button className="vs-project-card-title" onClick={()=>void open(project)} disabled={busy||project.archived}>{project.title}<span>{project.archived?'已归档':'打开工作台 ↗'}</span></button><p title={project.path}>{project.path}</p><div className="vs-project-card-meta"><span>{project.archivedAt?`归档于 ${localTime(project.archivedAt)}`:project.updatedAt?`更新于 ${localTime(project.updatedAt)}`:'本地工程'}</span>{controller.sourceDrafts(project.id).length>0&&<strong>{controller.sourceDrafts(project.id).length} 份源码草稿</strong>}</div><div className="vs-project-card-actions">{project.archived?<button disabled={busy} onClick={()=>void archive(project)}>恢复工程</button>:<><button disabled={busy} onClick={()=>{setManage({project,action:'rename'});setTitle(project.title);}}>重命名</button><button disabled={busy} onClick={()=>{setManage({project,action:'duplicate'});setTitle(`${project.title} 副本`);}}>复制工程</button><button disabled={busy} onClick={()=>void archive(project)}>归档</button></>}</div></article>)}</div>}
    {manage&&<div className="vs-modal-backdrop"><section className="vs-modal" role="dialog" aria-modal="true" aria-label={manage.action==='rename'?'重命名影片':'复制影片工程'}><div className="vs-section-header"><h2>{manage.action==='rename'?'重命名影片':'复制影片工程'}</h2><button aria-label="关闭工程操作" disabled={busy} onClick={()=>setManage(null)}>✕</button></div><label className="vs-field"><span>影片名称</span><input autoFocus aria-label="新的影片名称" value={title} onChange={event=>setTitle(event.target.value)}/></label>{manage.action==='duplicate'&&<p>副本包含已保存的分镜、源码和素材。原工程的会话、成片和未保存源码草稿保持在原工程中。</p>}{controller.getSnapshot().error&&<p className="vs-inline-error" role="alert">{controller.getSnapshot().error}</p>}<div className="vs-modal-actions"><button disabled={busy} onClick={()=>setManage(null)}>取消</button><button className="vs-primary" disabled={busy||!title.trim()} onClick={()=>void submit()}>{busy?'正在处理…':'保存'}</button></div></section></div>}
  </section>;
}
