import { useEffect, useState, useSyncExternalStore } from 'react';
import type { SceneSource, Shot } from '../shared/types.ts';
import type { StudioController } from './controller.ts';

function downloadDraft(name:string,source:SceneSource){const url=URL.createObjectURL(new Blob([JSON.stringify(source,null,2)],{type:'application/json;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=name+'-源码草稿.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function SourceEditor({controller,selectedShot,busy,version}:{controller:StudioController;selectedShot?:Shot;busy:boolean;version:string}){
  const state=useSyncExternalStore(controller.subscribe,controller.getSnapshot,controller.getSnapshot),project=state.snapshot?.project,projectId=project?.id;
  const [saved,setSaved]=useState<SceneSource|null>(null),[loadedRevision,setLoadedRevision]=useState(0),[language,setLanguage]=useState<'html'|'css'|'js'>('html'),[loading,setLoading]=useState(false),[error,setError]=useState(''),[reload,setReload]=useState(0),[confirm,setConfirm]=useState<'discard'|'restore'|null>(null);
  const draft=selectedShot?controller.getSourceDraft(selectedShot.id,projectId):undefined,source=draft?.source||saved;
  useEffect(()=>{let active=true;setSaved(null);setError('');setConfirm(null);if(!selectedShot){setLoading(false);return;}setLoading(true);const revision=controller.confirmedRevision??0;controller.readSource(selectedShot.id).then(value=>{if(active){setSaved(value);setLoadedRevision(revision);}}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'读取源码失败');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[controller,projectId,selectedShot?.id,version,reload]);
  const stale=!!draft&&draft.baseRevision!==(controller.confirmedRevision??draft.baseRevision);
  async function save(useCurrentRevision=false){if(!source||!selectedShot)return;const success=await controller.saveSource(selectedShot.id,source,useCurrentRevision);if(success){setSaved(source);setError('');setConfirm(null);}else setError(controller.getSnapshot().error||'源码尚未保存，草稿仍保留。');}
  async function restore(){if(!selectedShot)return;if(await controller.restoreSource(selectedShot.id)){setConfirm(null);setReload(value=>value+1);}else setError(controller.getSnapshot().error||'恢复失败，草稿仍保留。');}
  const drafts=controller.sourceDrafts(projectId);
  const shelf=drafts.length>0&&<div className="vs-source-draft-list"><span>本工程的源码草稿</span>{drafts.map(item=>{const shot=project?.shots.find(value=>value.id===item.shotId);return <div key={item.shotId}><button disabled={!shot} onClick={()=>controller.select(item.shotId)}>{shot?.title||'已移除镜头的草稿'}</button><button onClick={()=>downloadDraft(shot?.title||item.shotId,item.source)}>下载草稿</button>{!shot&&<button onClick={()=>controller.discardSourceDraft(item.shotId)}>丢弃草稿</button>}</div>;})}</div>;
  if(!selectedShot)return <div className="vs-source">{shelf}<div className="vs-dock-empty"><p>选中镜头查看与编辑前端源码。切换面板或离开 DSH 工作台会保留草稿。</p></div></div>;
  if(loading&&!draft)return <div className="vs-loading"><span className="vs-spinner"/>读取镜头源码…</div>;
  if(!source)return <div className="vs-source">{shelf}<p className="vs-inline-error" role="alert">{error||'未读取到源码。'}</p><button onClick={()=>setReload(value=>value+1)}>重试读取源码</button></div>;
  return <div className="vs-source">{shelf}<div className="vs-source-toolbar"><span>{selectedShot.title}</span><div className="vs-code-tabs">{(['html','css','js'] as const).map(item=><button key={item} className={language===item?'is-active':''} onClick={()=>setLanguage(item)}>{item.toUpperCase()}</button>)}</div><span className="vs-source-dirty">{draft?'草稿已保留 · 未提交':'源码已保存'}</span>{draft&&<button disabled={busy} onClick={()=>setConfirm('discard')}>丢弃草稿</button>}<button disabled={busy} onClick={()=>draft?setConfirm('restore'):void restore()}>恢复上次可用</button><button className="vs-primary" disabled={!draft||busy||stale} onClick={()=>void save()}>保存源码</button></div>
    {stale&&<div className="vs-source-stale" role="status"><span>草稿基于 v{draft!.baseRevision}，当前工程是 v{controller.confirmedRevision}。草稿已保留，请对照最新源码后再保存。</span><button disabled={busy} onClick={()=>void controller.load().then(()=>setReload(value=>value+1))}>读取最新工程</button><details><summary>查看已保存源码</summary><pre>{saved?.[language]||'正在读取…'}</pre></details><button disabled={busy||!saved} onClick={()=>void save(true)}>将草稿保存到当前版本</button></div>}
    {confirm&&<div className="vs-source-confirm" role="alert"><span>{confirm==='discard'?'丢弃这份草稿并返回已保存源码？':'恢复上次可用源码，并丢弃此草稿？'}</span><button onClick={()=>setConfirm(null)}>取消</button><button aria-label={confirm==='discard'?'确认丢弃源码草稿':'确认恢复上次源码'} disabled={busy} onClick={()=>{if(confirm==='discard'){controller.discardSourceDraft(selectedShot.id);setConfirm(null);setReload(value=>value+1);}else void restore();}}>{confirm==='discard'?'丢弃草稿':'恢复源码'}</button></div>}
    {error&&<p className="vs-inline-error" role="alert">{error}</p>}
    <textarea className="vs-code-editor" aria-label={`${language.toUpperCase()} 源码`} spellCheck={false} value={source[language]} onChange={event=>controller.setSourceDraft(selectedShot.id,{...source,[language]:event.target.value},loadedRevision)} onKeyDown={event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();if(draft&&!busy&&!stale)void save();}if(event.key==='Tab'){event.preventDefault();const field=event.currentTarget,start=field.selectionStart,end=field.selectionEnd,text=field.value;controller.setSourceDraft(selectedShot.id,{...source,[language]:text.slice(0,start)+'  '+text.slice(end)},loadedRevision);requestAnimationFrame(()=>field.setSelectionRange(start+2,start+2));}}}/>
    <p className="vs-source-note">源码草稿按工程与镜头保留，保存源码后才会进入预览与成片。Ctrl / ⌘ S 保存当前源码。</p>
  </div>;
}
